version: '3'

services:
#  api:
#    container_name: "authorizer-api"
#    build:
#      context: .
#      dockerfile: Dockerfile_dev
#    ports:
#      - 8080:8080
#    env_file:
#      api.env

  db:
    container_name: "authorizer_db"
    image: postgres:12
    ports:
      - 5432:5432
    env_file:
      - db.env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    external: true